# The Docker Config version. Do not change.
version: "3"
services:
  mysqldb:
    image: mysql:8
    # This appears to count as the database name as well
    container_name: speedwaydb
    volumes:
      - speedwaydata:/var/lib/mysql
    networks:
      - speedwaynet
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: speedway_trials
      # Create user; requires a new volume. Will not create on existing volumes.
      MYSQL_USER: speedracer
      MYSQL_PASSWORD: zoom
    ports:
#     Map local port 3307 to container port 3306 to prevent conflict with local MySQL
      - "3307:3306"
  api:
    # REPLACE registry/repo:tag with your registry and repo details
    image: lotech/speedway_api:latest
    container_name: speedway_api
    depends_on:
      - mysqldb
    restart: always
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - speedwaynet

volumes:
  speedwaydata:
    driver: local

networks:
  speedwaynet: