# The Docker Config version. Do not change.
version: "3"
services:
  mysqldb:
    image: mysql:8
    container_name: speedwaydb
    volumes:
      - speedwaydata:/var/lib/mysql
    networks:
      - speedwaynet
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: speedway_trials
      # Create user; requires a new volume. Will not create on existing volumes.
      MYSQL_USER: speedracer
      MYSQL_PASSWORD: zoom
    ports:
    # Map local port 3307 to container port 3306 to prevent conflict with local MySQL
      - "3307:3306"
  api:
    image: lotech/speedway_api:latest
    container_name: speedway_api
    environment:
      DB_USER: speedracer
      DB_PASSWORD: zoom
      DB_PWD: zoom
    depends_on:
      - mysqldb
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - speedwaynet
# Persists data across deployments so database isn't lost
volumes:
  speedwaydata:
    driver: local
# Defines a shared network for all services to connect them and share data
networks:
  speedwaynet: